[workspace]
resolver = "2"

members = [
    "tools/axlibc",
    "apps/display",
    "apps/exception",
    "apps/helloworld",
    "apps/memtest",
    "apps/fs/shell",
    "apps/net/echoserver",
    "apps/net/httpclient",
    "apps/net/httpserver",
    "apps/net/udpserver",
    "apps/net/bwbench",
    "apps/task/parallel",
    "apps/task/sleep",
    "apps/task/yield",
    "apps/task/priority",
    "apps/task/tls",
    "apps/monolithic_userboot"
]

[profile.release]
lto = true

[profile.dev]
lto = true

[patch."https://github.com/rcore-os/smoltcp.git"]
smoltcp = { git = "https://github.com/c0per/smoltcp", branch = "starryos" }
