site_name: Starry
site_description: Starry设计文档
nav:
  - Starry: index.md
  - 1.概述: 1.概述/1.1背景.md
  - 2.架构设计: 
    - 2.1 ArceOS介绍: 2.架构设计/2.1ArceOS介绍.md
    - 2.2 Starry结构说明: 2.架构设计/2.2Starry结构说明.md
  - 3.设计思路: 
    - 3.1 模块划分: 3.设计思路/3.1模块划分.md
    - 3.2 进程引入: 3.设计思路/3.2进程引入.md
    - 3.3 地址空间引入: 3.设计思路/3.3地址空间引入.md
    - 3.4 特权级切换: 3.设计思路/3.4特权级切换.md
  - 4. 模块介绍:
    - 4.1 内核底层模块-axhal: 4.模块介绍/4.1内核底层模块-axhal.md
    - 4.2 设备驱动模块-axdriver: 4.模块介绍/4.2设备驱动模块-axdriver.md
    - 4.3 内存管理模块-axmem: 4.模块介绍/4.3内存管理模块-axmem.md
    - 4.4 网络模块-axnet: 4.模块介绍/4.4网络模块-axnet.md
    - 4.5 信号模块-axsignal: 4.模块介绍/4.5信号模块-axsignal.md
    - 4.6 任务调度模块-axtask: 4.模块介绍/4.6任务调度模块-axtask.md
    - 4.7 文件系统模块-axfs: 4.模块介绍/4.7文件系统模块-axfs.md
    - 4.8 进程控制模块-axprocess: 4.模块介绍/4.8进程控制模块-axprocess.md
    - 4.9 内核运行时模块-axruntime: 4.模块介绍/4.9内核运行时模块-axruntime.md
    - 4.10 宏内核用户库-starry: 4.模块介绍/4.10宏内核用户库-starry.md
  - 5. 实现重点:
    - 5.1 依赖问题: 5.实现重点/5.1依赖问题.md
    - 5.2 兼容问题: 5.实现重点/5.2兼容问题.md
  - 6. 问题与解决:
    - 6.1 问题: 6.问题与解决/6.1问题.md

# 主题
# theme:
#   name: 'material'
#   language: 'zh'  # 配置语言
#   palette: # 颜色
#     primary: 'purple'
#     accent: 'indigo'
#   feature:
#     tabs: true  # 横向导航

# [UI]
theme:
  name: material
  palette:
    #primary: blue grey
  
    - scheme: default # 日间模式
      primary: grey # 上方的
      accent: cyan # 链接等可交互元件的高亮色
      toggle:
        icon: material/weather-night # 图标
        name: 切换至夜间模式 # 鼠标悬浮提示
    - scheme: slate # 夜间模式
      primary: black 
      accent: cyan
      toggle:
        icon: material/weather-sunny
        name: 切换至日间模式

markdown_extensions:
  - admonition  # 提示块
  - footnotes  # 脚注
  - meta  # 定义元数据，通过文章上下文控制，如disqus
  - pymdownx.caret  # 下划线上标
  - pymdownx.tilde  # 删除线下标
  - pymdownx.critic  # 增加删除修改高亮注释，可修饰行内或段落
  - pymdownx.details  # 提示块可折叠
  - pymdownx.inlinehilite  # 行内代码高亮
  - pymdownx.mark  # 文本高亮
  - pymdownx.smartsymbols  # 符号转换
  - pymdownx.superfences  # 代码嵌套在列表里
  - codehilite:    # 代码高亮，显示行号
      guess_lang: false
      linenums: true
  - toc:  # 锚点
      permalink: true
#  - pymdownx.arithmatex  # 数学公式
  # - pymdownx.betterem:  # 对加粗和斜体更好的检测
  #     smart_enable: all
#  - pymdownx.emoji:  # 表情
#      emoji_generator: !!python/name:pymdownx.emoji.to_svg
#  - pymdownx.magiclink  # 自动识别超链接
  - pymdownx.tasklist:  # 复选框checklist
      custom_checkbox: true

# PDF导出插件
plugins:
  - search
#  - pdf-export #这个插件还有点问题，没有更新

#扩展样式
extra_css:
  - resources/css/extra.css